### ISSUE TITLE
SWTPG validation: Found in total 0 hits.

### ISSUE THREAD

**Issue by hristovaivana** [DUNE-DAQ/fdreadoutlibs#105]
Hi Adam,
I would like to report that there are no hits found when currently running the SWTPG test application from the following branch and the way I run the test application (it could be my problem with the setup). 
https://github.com/DUNE-DAQ/fdreadoutlibs/tree/tpg_validation_tools

I use the following input file, but please let us know if we should load another file or generate our own input file. In the latter case, it would be helpful to post to command to generate the file so that it is the same for everyone. 
`assets-list --label DuneWIB --subsystem=readout`
`cp /cvmfs/dunedaq.opensciencegrid.org/assets/files/e/2/f/wib2-frames.bin .`

To run the test application:
`TestSWTPGAlgorithms -f wib2-frames.bin -a SWTPG -i NAIVE -n 4 -t 100 --save_adc_data false --save_hit_data true`
which produces at the end

`===============================
Found in total 0 hits.`

I suspect there are several things to check:
1. Whether the correct channel map is used for this particular bin file
2. Whether the threshold option from the command line is propagated to the algorithm

**Comment by adam-abed-abud** [comment]
Hi Ivana! 
1) The channel mapping is hardcoded in the "SwtpgBase.hpp" class (https://github.com/DUNE-DAQ/fdreadoutlibs/blob/tpg_validation_tools/test/apps/SwtpgTest/SwtpgBase.hpp). It uses as default `HDColdboxChannelMap`. Maybe you can fix this and make it configurable from the command line? 
2) The threshold command is indeed propagated to the algorithm. Have you tried changing the value of the threshold and see what happens? 

Thanks, 
Adam

**Comment by hristovaivana** [comment]
Hi Adam!

Thank you for the very useful comments. I have done the following changes in my latest branch
https://github.com/DUNE-DAQ/fdreadoutlibs/tree/hristova/hit_peak_adc_and_time_fix

1. I've added an option to allow us to provide the offline channel map name at the command line, as you suggested 
`TestSWTPGAlgorithms -h`

2. The fix for the peak ADC and peak time of the TriggerPrimitive is also fixed and tested. 
https://github.com/DUNE-DAQ/fdreadoutlibs/issues/89

Thanks,
Ivana

**Comment by adam-abed-abud** [comment]
Hi Ivana, 
Thanks for the nice changes. Do we still get 0 hits after fixing and properly selecting the correct offline channel map? 
Adam

**Comment by hristovaivana** [comment]
Hi Adam,

Thanks for asking this because I forgot to mention. The problem with the found hits being 0 is solved indeed. In the most 
recent tests with the application I also see positive correlation between the threshold value and the hits found, which 
confirmed that the threshold is propagated correctly. Since this Issue was opened because of the problem with the hits, 
we can now close it. 

Cheers,
Ivana

**Comment by adam-abed-abud** [comment]
Hi Ivana,

I'm going to close the issue and follow up the fix on issue #89 .

Thanks,
Adam
