### ISSUE TITLE
request for new config param for WIBEthFrameProcessor for enabling WIB ADC pattern data

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/fdreadoutlibs#124]
In WIBEthFrameProcessor, the _emulator_mode_ flag is overloaded to enable the modification of the WIB ADC data (in addition to its existing behavior of enabling the over-writing of the timestamps in the WIB data).  I found it confusing to have the `emulator_mode` flag grow this new meaning without any advertisement of the new functionality.

I would request a new, separate flag to control the over-writing of the ADC data.  Something like `generate_periodic_adc_pattern_data`.  And, it might be useful to be able to configure the rate of generation of pattern data (compared to the fixed rate that is provided now).

**Comment by adam-abed-abud** [comment]
I have a made the change to add a separate flag control to avoid using the `emulator_mode` flag. The change is in the branch `aabedabu/generate_adc_pattern` and it is available in `daqconf`, `readoutlibs` and `fdreadoutlibs`. 

If needed I will also add a configuration parameter to control the rate generation
