### ISSUE TITLE
Move implementations (methods, funcs) from headers to source files

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/fdreadoutlibs#15]
Most of the `fdreadoutlibs` code is in header files without being strictly needed. This has a number of disadvantages, including code readability (class structure, typically) and lack of coverage during compilation.
The code should be reorganized along the usual split between hpp and cpp files.
Also, it is worth considering splitting some files like [FDReadoutTypes.hpp](https://github.com/DUNE-DAQ/fdreadoutlibs/blob/develop/include/fdreadoutlibs/FDReadoutTypes.hpp) which contain multiple complex object definitions.

**Comment by roland-sipos** [comment]
Have a branch also for `readoutlibs`:
https://github.com/DUNE-DAQ/readoutlibs/tree/roland-sipos/decl-separation

Soon there will be PRs on both packages.
