### ISSUE TITLE
Ghost TPs at VD coldbox

### ISSUE THREAD

**Issue by adam-abed-abud** [DUNE-DAQ/fdreadoutlibs#170]
During the coldbox runs in week 15 (April 8th to 15th) we noticed that some TPs point to a non existing detector activity. See attached images: 
![problem_fig1](https://github.com/DUNE-DAQ/fdreadoutlibs/assets/29180717/d0abec06-56b4-4831-aaab-dd456b739bdc)
![problem_fig2](https://github.com/DUNE-DAQ/fdreadoutlibs/assets/29180717/1ef15186-24b3-4398-ae30-dd4e45ddfe0b)

**Comment by aeoranday** [comment]
Closed by @adam-abed-abud's fix.
