### ISSUE TITLE
Fix loop lunacy in TP sending code

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/fdreadoutlibs#195]
This loop loop loop loop mess is just so horrible and painful right before the try_send:
https://github.com/DUNE-DAQ/fdreadoutlibs/blob/77ebc73e223642181f365468bacd13554cb0cc08/src/wibeth/WIBEthFrameProcessor.cpp#L513

Adapt something like this:

```
struct HitData {
  uint16_t chan;
  uint16_t hit_end;
  uint16_t hit_charge;
  uint16_t hit_tover;
  uint16_t hit_peak_time;
  uint16_t hit_peak_adc;
  uint16_t left;
};

std::array<HitData, 16> hit_data;
unsigned int nhits = 0;

while (*primfind_it != swtpg_wibeth::MAGIC) {
  for (auto& hit : hit_data) {
    hit.chan = *primfind_it++;
    hit.hit_end = *primfind_it++;
    hit.hit_charge = *primfind_it++;
    hit.hit_tover = *primfind_it++;
    hit.hit_peak_adc = *primfind_it++;
    hit.hit_peak_time = *primfind_it++;
    hit.left = *primfind_it++;
  }
}
```

**Comment by roland-sipos** [comment]
I just realized the sequence is important. To be investigated if it's possible to have a better data structure for primfind_it...

**Comment by aeoranday** [comment]
Resolved by https://github.com/DUNE-DAQ/tpglibs.
