### ISSUE TITLE
New FW TP format support

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/fdreadoutlibs#26]
This is a first step towards supporting the new FW TP output format.

Keep the current code design, including RAW_WIB_TRIGGERPRIMITIVE_STRUCT as it stands.
Add code to parse the new format in RAWWIBTriggerPrimitiveProcessor, as a configurable option (old vs new format).

In a later step, we can streamline the code design and improve efficiency, but that can come in a later step.

**Comment by jimbrooke** [comment]
unable to assign issues here - this is another one for @hristovaivana

**Comment by hristovaivana** [comment]
This implemented in the following branches (PRs):
https://github.com/DUNE-DAQ/fdreadoutlibs/pull/46
https://github.com/DUNE-DAQ/readoutlibs/pull/49
https://github.com/DUNE-DAQ/readoutmodules/pull/28

**Comment by roland-sipos** [comment]
Can this be closed @hristovaivana ?

**Comment by hristovaivana** [comment]
@roland-sipos thanks, yes, this can be closed.
