### ISSUE TITLE
Make FW TP stitching options configurable

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/fdreadoutlibs#27]
Eg clock frequency

**Comment by hristovaivana** [comment]
I started working on this and I have a configuration working with initial/default values of the configurable parameters. 

To make the configuration simpler and non-redundant. it would be good to clarify which are the basic 
system parameters and those that can be derived from them. In addition we need to understand better the exact values 
of the parameters for operation with the WIB2. I had in-person discussion with Kostas (he is not on github) but we can 
continue the discussion on the Slack channel and at the weekly meeting..

**Comment by jimbrooke** [comment]
done
