### ISSUE TITLE
Add rate monitoring for FW TPs

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/fdreadoutlibs#28]
This could include rates of raw TPs and stitched TPs

**Comment by jimbrooke** [comment]
I'm no longer able to assign issues in this repo, I guess permissions have changed - this should be assigned to @hristovaivana

**Comment by roland-sipos** [comment]
Assignment updated.

**Comment by roland-sipos** [comment]
Closing issue as won't-fix
