### ISSUE TITLE
TP stream data seems to have wrong SourceID Subsystem for emuliated WIB (wib2) data

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/fdreadoutlibs#65]
I noticed that the SourceID Subsystem type is not being set correctly in the TPStream for WIB2 data.

For this, I used the following daqconf.json file:
```
{
  "dataflow": {
      "apps": [
          { "app_name": "dataflow0" },
          { "app_name": "dataflow1" }
      ]
  },
  "readout": {
    "enable_software_tpg": true,
    "data_rate_slowdown_factor": 10,
    "clock_speed_hz": 62500000,
    "data_file": "./wib2-frames.bin",
    "readout_sends_tp_fragments": false
  },
  "trigger": {
    "enable_tpset_writing": true,
    "trigger_activity_config": {"prescale":1000},
    "trigger_window_before_ticks": 1250,
    "trigger_window_after_ticks": 1250,
    "trigger_rate_hz": 1.0
  }
}
```

and the following hw_map.txt file:
```
# DRO_SourceID DetLink DetSlot DetCrate DetID DRO_Host DRO_Card DRO_SLR DRO_Link 
100 0 4 6 3 localhost 0 0 0
101 1 4 6 3 localhost 0 0 1
```

I then used the following steps:
```
daqconf_multiru_gen -c ./daqconf.json --hardware-map-file ./hw_map.txt mdapp_tpsw
curl -o wib2-frames.bin https://cernbox.cern.ch/index.php/s/ocrHxSU8PucxphE/download
nanorc mdapp_tpsw ${USER}-test boot conf start_run 111 wait 30 stop_run scrap terminate
HDF5LIBS_TestDumpRecord tpstream_run000111_0000_tpwriter_tpswriter_*.hdf5
```

The dump-record output showed results like the following:
```
2022-Oct-20 10:13:40,282 LOG [main(...) at /tmp/root/spack-stage/spack-stage-hdf5libs-v2.3.2-nddkh66ugwntxrolllv7symtsbi3ao77/spack-src/test/apps/HDF5LIBS_TestDumpRecord.cpp:118] 
	TimeSliceHeader: check_word: 55556666, version: 2, timeslice_number: 30, run_number: 111, element_id: { subsystem: TR_Builder id: 2 }
	Trigger_Primitive fragment with SourceID Detector_Readout_0x00000064 from subdetector DAQ has size = 4557184
		It may contain data from the following detector components:
			subdetector HD_TPC, crate 6, slot 4, link 0
	Trigger_Primitive fragment with SourceID Detector_Readout_0x00000065 from subdetector DAQ has size = 4557184
		It may contain data from the following detector components:
			subdetector HD_TPC, crate 6, slot 4, link 1
```

In those results, we see "SourceID Detector_Readout..." when we should be seeing "SourceID Trigger_..."

I'm going to label this Issue as a bug since I know that this scenario works correctly when we use emulated ProtoWIB data instead of emulated WIB data.  I'm also going to assign it to the 3.2.1 release since it seems like something that we should fix for that release.

I tried to look at the changes in daqconf, readoutlibs, and fdreadoutlibs that were made to fix this problem for emulated ProtoWIB data, but I got bogged down by the fact that the tpset_sourceid config param is used by fdreadoutlibs/wib/WIBFrameProcessor.hpp for ProtoWIB, but for WIB it is used by fdreadoutlibs/wib2/RAWWIBTriggerPrimitiveProcessor.hpp and other things that I didn't understand.

**Comment by glehmannmiotto** [comment]
fixed in branch aabedabu/swtpg_refactor

**Comment by roland-sipos** [comment]
Closed by swtpg_refactor.
