### ISSUE TITLE
SW : Integrate FW trigger primitives into readout

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/fdreadoutlibs#9]
This is a fast and slightly dirty way to integrate firmware TPs.
This corresponds to PR https://github.com/DUNE-DAQ/fdreadoutlibs/pull/10 

1. the ReadoutType will hold the data in a std::vector < std::uint8_t >.
2. the latency buffer and recording therefore just deals in FELIX frames. Note that a FELIX frame, with superchunking set to >1, will store multiple TP hit frames.
3. there is no conversion from the "old" TP hit frame format to the "new" TP hit frame format.
4. the post-processing step in RAWWIBTriggerPrimitiveProcessor will include extraction of TPs/hits from the FELIX frames, and stitching TPs together

**Comment by jimbrooke** [comment]
@roland-sipos this describes code that is almost working from Ivana on https://github.com/DUNE-DAQ/fdreadoutlibs/tree/hristova/tp_superchunking

It would be good to understand if there are potential showstoppers, and/or whether any part of the proposal is unacceptable.

If any part of the proposal is unclear, let's discuss.

**Comment by hristovaivana** [comment]
There is a PR to address this task
https://github.com/DUNE-DAQ/fdreadoutlibs/pull/10
