### ISSUE TITLE
Fix of TPG rate and TPSet rate on grafana

### ISSUE THREAD

**Issue by adam-abed-abud** [DUNE-DAQ/fdreadoutlibs#96]
The orange and green lines show the same quantity but calculated in a different way. This is confusing. The orange line is not needed at all and the rate is even calculated inside the code.

![image](https://user-images.githubusercontent.com/29180717/229837599-7ee237db-b04f-4442-b0ee-c5775c12d842.png)

**Comment by mroda88** [comment]
I'm closing the issues as the plot does not exist anymore.
